### ISSUE TITLE
WebAssembly/Android/IOS compilation?

### ISSUE THREAD

**Issue by Lelfy** [superjer/tinyc.games#2]
Hello, that's an amazing project! I'm learning SDL and searched a lot for a simple, cross-platform barebones SDL sample games made in C, that can be compiled in TCC and uses a permissive license (Such as MIT) yours were one of the few i found. :)

Do you have any plans to add sh scripts for WebAssembly/Android/IOS compilation? Or write/recommend a guide on how these can be done for this specific project? Thank you!

**Comment by superjer** [comment]
I don't have any experience with WebAssembly/Android/IOS. I don't know what to recommend either. I hope you found something by now!
