### ISSUE TITLE
Windows versions giving errors

### ISSUE THREAD

**Issue by phillipeaton** [superjer/tinyc.games#5]
Hello,

I'm new to C and SDL and I'm trying to compile the example games on Windows 10 64-bit, but unfortunately, they're failing. 

i've git cloned the tinyc.games folder and executed "run.windows" for all the games and they all fail, mostly with the below errors:

Am I doing something stupid?

Thanks for any advice!
```
C:\tinyc.games\zel>run-windows.bat
..\_win\tcc-x64\tcc.exe
The system cannot find the path specified.
tcc: error: undefined symbol 'SDL_SetRenderDrawColor'
tcc: error: undefined symbol 'SDL_RenderFillRect'
tcc: error: undefined symbol 'SDL_RenderCopy'
tcc: error: undefined symbol 'SDL_SetRenderDrawBlendMode'
tcc: error: undefined symbol 'SDL_RenderPresent'
tcc: error: undefined symbol 'SDL_PollEvent'
tcc: error: undefined symbol 'SDL_Delay'
tcc: error: undefined symbol 'SDL_Init'
tcc: error: undefined symbol 'SDL_CreateWindow'
tcc: error: undefined symbol 'SDL_CreateRenderer'
tcc: error: undefined symbol 'SDL_RWFromFile'
tcc: error: undefined symbol 'SDL_LoadBMP_RW'
tcc: error: undefined symbol 'SDL_SetColorKey'
tcc: error: undefined symbol 'SDL_CreateTextureFromSurface'
tcc: error: undefined symbol 'TTF_Init'
tcc: error: undefined symbol 'TTF_OpenFont'
```

**Comment by willbr** [comment]
That looks like TCC can't find `SDL2.dll`

Try copying it into zel folder. And, then run the script again.

`The system cannot find the path specified.`

Means something is failing in the `run-windows.bat` script.

Try changing the first line to `@echo on` to enable verbose output in the script.

**Comment by phillipeaton** [comment]
Thanks for the tip, I tried adding the 'SDL2.dll' to the directories with 'run-windows.bat' files the and half of the programs now compile and run. (The other half still fail.)

I'm not sure this repository qualifies as "Tiny C games you can compile and run RIGHT NOW.", at least not for Windows users, but it has helped me with I'm trying to do. 👍
